apiVersion: v1
data:
  frontend.jsonnet: |
    local common = import 'common.libsonnet';

    {
      blobstore: common.blobstore,
      grpcServers: [{
        listenAddresses: [':8980'],
        authenticationPolicy: { allow: {} },
      }],
      schedulers: {
        '': { endpoint: { address: 'scheduler:8982' } },
      },

      maximumMessageSizeBytes: common.maximumMessageSizeBytes,
    }
kind: ConfigMap
metadata:
  name: frontend
  namespace: {{ .Values.deployment.namespace }}