---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: browser
  namespace: {{ .Values.deployment.namespace }}
spec:
  replicas: {{ .Values.deployment.browserReplicaCount }}
  selector:
    matchLabels:
      app: browser
  template:
    metadata:
      labels:
        app: browser
    spec:
      containers:
      - image: {{ .Values.deployment.browserImage }}
        args:
        - /config/browser.jsonnet
        name: browser
        ports:
        - containerPort: 80
          protocol: TCP
        volumeMounts:
        - mountPath: /config/
          name: configs
          readOnly: true
      volumes:
      - name: configs
        projected:
          sources:
          - configMap:
              name: browser
              items:
              - key: browser.jsonnet
                path: browser.jsonnet
          - configMap:
              name: common
              items:
              - key: common.libsonnet
                path: common.libsonnet