---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: browser
  namespace: {{ .Values.deployment.namespace }}
spec:
  rules:
  - host: {{ .Values.deployment.browserHostName }}
    http:
      paths:
      - path: /
        backend:
          serviceName: browser
          servicePort: 80