---
apiVersion: v1
kind: Service
metadata:
  name: browser
  namespace: {{ .Values.deployment.namespace }}
  annotations:
    prometheus.io/port: "80"
    prometheus.io/scrape: "true"
spec:
  ports:
  - port: 80
    protocol: TCP
    name: http
  selector:
    app: browser
  type: ClusterIP